language: python
python:
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
script: pytest
after_sucess:
  - CODECLIMATE_REPO_TOKEN=ab7fa82983fba1afa288a66692c6e990a47b3db7 codeclimate-test-reporter