language: python
python:
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
script: pytest
after_sucess:
  - CODECLIMATE_REPO_TOKEN=5f25bee4e98640b6166792545f7914964569db3e1ec287937d43b4838422abb9 codeclimate-test-reporter